[build]
  command = "npm run dev"
  publish = "dist"      
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]

[[redirects]]
  from = "/*"
  to = "/netlify/functions/index" 
  status = 200
  force = true
